name: Setup Terraform
description: Installs terraform and Configure AWS
inputs:
  role_to_assume:
    description: 'Role to use for AWS configure'
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
