name: Terraform AWS Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  PLAN_FILE: "tfplan"
  TF_WORKINGSPACE: github-aws-quest

defaults:
  run:
    working-directory: aws-terraform

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform:
    name: Apply or Delete AWS Resources
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
         aws-region: us-east-1
  
      - name: Terraform Init
        run: terraform init
      
      - name: Select Terraform Workspace
        run: terraform workspace select ${{ env.TF_WORKINGSPACE }} || terraform workspace new ${{ env.TF_WORKINGSPACE }}
      
      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform plan -input=false -out=${{ env.PLAN_FILE }}
          else
            terraform plan -destroy -input=false -out=${{ env.PLAN_FILE }}
          fi
      
      - name: Wait for Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: cloudkarthik99
          issue-title: "Manual Approval Required for AWS Terraform Apply or Deny"
          issue-body: "Please approve or deny the deployment."

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply --input=false "${{ env.PLAN_FILE }}"

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform apply --input=false "${{ env.PLAN_FILE }}"