name: Terraform GCP Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PLAN_FILE: "tfplan"
  TF_WORKINGSPACE: github-gcp-quest
  IDENTITY_PROVIDER: ${{ secrets.GCP_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GKE_CLUSTER: ${{ secrets.GCP_GKE_CLUSTER_QUEST}}
  GCP_REGION: "us-east1-b"

defaults:
  run:
    working-directory: gcp-terraform

permissions:
  id-token: write
  contents: read
  issues: write
  
jobs: 
  terraform:
    name: Apply or Delete GCP Resources
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'kubectl'
      
      - name: Terraform Init
        run: terraform init
      
      - name: Select Terraform Workspace
        run: terraform workspace select ${{ env.TF_WORKINGSPACE }} || terraform workspace new ${{ env.TF_WORKINGSPACE }}

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform plan -input=false -out=${{ env.PLAN_FILE }} -detailed-exitcode; exitcode=$?
          else
            terraform plan -destroy -input=false -out=${{ env.PLAN_FILE }} -detailed-exitcode; exitcode=$?
          fi
          
          echo "Exit code: $exitcode"
    
          if [ "$exitcode" -eq 2 ]; then
            echo "Changes detected in plan" 
            echo "CHANGES_PRESENT=true" >> $GITHUB_ENV
          else
            echo "No Changes detected in plan" 
            echo "CHANGES_PRESENT=false" >> $GITHUB_ENV
          fi

      - name: Wait for Approval
        if: ${{ env.CHANGES_PRESENT == 'true' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: cloudkarthik99
          issue-title: "Manual Approval Required for GCP Terraform Apply or Deny"
          issue-body: "Please approve or deny the deployment."
      
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' && env.CHANGES_PRESENT == 'true' }}
        run: |
          terraform apply --input=false "${{ env.PLAN_FILE }}"
      
      - name: No Changes in Terraform Apply state
        if: env.CHANGES_PRESENT == 'false'
        run: echo "No changes detected in Terraform plan. Skipping approval and apply steps."

      - name: Get GKE Cluster Credentials
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
         cluster_name: ${{ env.GKE_CLUSTER }}
         location: ${{ env.GCP_REGION }}
         project_id: ${{ env.PROJECT_ID }}
      
      - name: Deploy Kubernetes Manifests
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          kubectl apply -f manifests/namespace.yaml
          sleep 30s
          kubectl apply -f manifests/

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform apply --input=false "${{ env.PLAN_FILE }}"


